module.exports = {
  TELEGRAM: {
    TOKEN: 'TELEGRAM_BOT_TOKEN'
  },
  COINMARKETCAP: {
    API_KEY: 'CMC_PRO_API_KEY'
  },
  COINMARKETCAL: {
    CLIENT_ID: 'CLIENT_ID',
    CLIENT_SECRET: 'CLIENT_SECRET'
  }
}
